name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.channel == 'nightly' }}
    steps:
      - uses: actions/checkout@v4

      - name: install
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s ${{ matrix.channel }}
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install on windows
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          MOONBIT_INSTALL_VERSION: ${{ matrix.channel }}
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: install deps
        run: | 
          moon update
          moon check --deny-warn

      - name: moon check
        run: moon check 

      - name: moon info
        run: |
          moon info --target all
          git diff --exit-code
      
      - name: download testsuite (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
        run: sh scripts/init.sh

      - name: download testsuite (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: ./scripts/init.ps1

      - name: Setup MSVC
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run moon test
        run: |
          moon test --target all
          moon test --release --target all
